name: capex
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - ca-certificates=2024.3.11
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.4.99
  - cuda-runtime=12.1.0
  - cudatoolkit=11.8.0
  - filelock=3.13.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - intel-openmp=2023.1.0
  - jinja2=3.1.3
  - ld_impl_linux-64=2.38
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.9.0.20
  - libcurand=10.3.5.119
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libnpp=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libstdcxx-ng=11.2.0
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - networkx=3.1
  - openssl=3.0.13
  - pip=23.3.1
  - python=3.8.18
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - sympy=1.12
  - tbb=2021.8.0
  - tk=8.6.12
  - typing_extensions=4.9.0
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - addict==2.4.0
      - aiofiles==23.2.1
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - altair==5.3.0
      - annotated-types==0.6.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.3.0
      - async-timeout==4.0.3
      - attrs==23.2.0
      - cachetools==5.3.3
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - chumpy==0.70
      - click==8.1.7
      - git+https://github.com/openai/CLIP.git
      - contourpy==1.1.1
      - cycler==0.12.1
      - cython==3.0.9
      - dnspython==2.6.1
      - email-validator==2.1.1
      - exceptiongroup==1.2.1
      - fastapi==0.111.0
      - fastapi-cli==0.0.3
      - ffmpy==0.3.2
      - fonttools==4.49.0
      - frozenlist==1.4.1
      - fsspec==2024.2.0
      - ftfy==6.2.0
      - future==1.0.0
      - google-auth==2.28.2
      - google-auth-oauthlib==1.0.0
      - gradio==4.31.0
      - gradio-client==0.16.2
      - grpcio==1.62.1
      - h11==0.14.0
      - httpcore==1.0.5
      - httptools==0.6.1
      - httpx==0.27.0
      - huggingface-hub==0.21.4
      - idna==3.6
      - importlib-metadata==7.0.1
      - importlib-resources==6.1.2
      - joblib==1.4.0
      - json-tricks==3.17.3
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.5
      - kornia==0.7.2
      - kornia-rs==0.1.3
      - lightning-utilities==0.11.2
      - markdown==3.5.2
      - markdown-it-py==3.0.0
      - matplotlib==3.7.5
      - mdurl==0.1.2
      - mmcv-full==1.6.2
      - mmpose==0.29.0
      - multidict==6.0.5
      - munkres==1.1.4
      - numpy==1.24.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.4.99
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - opencv-python==4.9.0.80
      - orjson==3.10.3
      - packaging==23.2
      - pandas==2.0.3
      - pillow==10.2.0
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.2.0
      - protobuf==4.25.3
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pydantic==2.7.1
      - pydantic-core==2.18.2
      - pydub==0.25.1
      - pygments==2.18.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-multipart==0.0.9
      - pytorch-lightning==2.2.1
      - pytz==2024.1
      - pyyaml==6.0.1
      - referencing==0.35.1
      - regex==2023.12.25
      - requests==2.31.0
      - requests-oauthlib==1.4.0
      - rich==13.7.1
      - rpds-py==0.18.1
      - rsa==4.9
      - ruff==0.4.4
      - safetensors==0.4.2
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - semantic-version==2.10.0
      - sentencepiece==0.2.0
      - shellingham==1.5.4
      - six==1.16.0
      - sniffio==1.3.1
      - starlette==0.37.2
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.4.0
      - timm==0.4.12
      - tokenizers==0.15.2
      - tomli==2.0.1
      - tomlkit==0.12.0
      - toolz==0.12.1
      - torch==2.2.1
      - torchmetrics==1.3.2
      - torchvision==0.17.1
      - tqdm==4.66.2
      - transformers==4.38.2
      - triton==2.2.0
      - typer==0.12.3
      - tzdata==2024.1
      - ujson==5.9.0
      - urllib3==2.2.1
      - uvicorn==0.29.0
      - uvloop==0.19.0
      - watchfiles==0.21.0
      - wcwidth==0.2.13
      - websockets==11.0.3
      - werkzeug==3.0.1
      - xtcocotools==1.14.3
      - yapf==0.40.1
      - yarl==1.9.4
      - zipp==3.17.0
